"""
Django settings for FileCollector project.

Generated by 'django-admin startproject' using Django 4.1.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-i=9h^%^$+@=3-_s9x#zteis+2@ss)ltr=kn3gnflza5p=r2571'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ['*']

# Application definition

INSTALLED_APPS = [
    'collector.apps.CollectorConfig',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'FileCollector.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates']
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'FileCollector.wsgi.application'

# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

# make sure to change the database setting to your own
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'FileCollector',
        'USER': 'root',
        'PASSWORD': 'your_password',
        'HOST': 'your_host',
        'PORT': 'your_port',
    }
}

# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/Chongqing'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, "static")

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

SESSION_ENGINE = 'django.contrib.sessions.backends.signed_cookies'

SESSION_COOKIE_HTTPONLY = True

# 项目配置(注:上文中的Database也需要修改成自己的数据库路径)

VALID_TIME = 300  # 短信验证码有效时间(秒)

ACTIVE_TIME = 7200  # 用户登录活跃有效时间(秒)

# 腾讯云API密钥，请确保已开通短信服务，用于发送短信
TENCENT_SECRET_ID = 'your_secret_id'
TENCENT_SECRET_KEY = 'your_secret_key'

# 项目将哪个文件夹作为外界用户访问的根目录
HOME_PATH = os.path.join(os.path.expanduser("~"), 'Desktop')
ZIP_FILE_PATH = os.path.join(os.path.expanduser("~"), 'Desktop/temp')
# 创建文件夹
if not os.path.exists(ZIP_FILE_PATH):
    os.makedirs(ZIP_FILE_PATH)
if not os.path.exists(HOME_PATH):
    os.makedirs(HOME_PATH)

# 项目默认管理员账号(如果需要添加其他成员为管理员，需要在数据库中手动设置权限或者在后台/admin中添加)
ROOT_USER_NAME = '管理员'
ROOT_USER_PASSWORD = '123456'
ROOT_USER_PHONE = '管理员'

# 上传文件的最大大小(单位:B)
UPLOAD_MAX_SIZE = 1024 * 1024 * 100  # 100 MB
